"""catalog: seasons, clubs, players, gameweeks, fixtures

Revision ID: 733c795e4cc6
Revises: 
Create Date: 2026-08-02 23:32:13.312426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '733c795e4cc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('source', sa.Enum('EXCEL', 'API', 'SEED', name='sourcekind'), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_club_code'), ['club_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_club_source'), ['source'], unique=False)

    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_code'), ['code'], unique=True)

    op.create_table('gameweek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('deadline_utc', sa.DateTime(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'number', name='uq_gameweek_season_number')
    )
    with op.batch_alter_table('gameweek', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gameweek_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_gameweek_season_id'), ['season_id'], unique=False)

    op.create_table('player',
    sa.Column('source', sa.Enum('EXCEL', 'API', 'SEED', name='sourcekind'), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Enum('GK', 'DEF', 'MID', 'FWD', name='position'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INJURED', 'SUSPENDED', 'UNAVAILABLE', name='playerstatus'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_player_code'), ['player_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_player_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_status'), ['status'], unique=False)

    op.create_table('fixture',
    sa.Column('source', sa.Enum('EXCEL', 'API', 'SEED', name='sourcekind'), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(), nullable=False),
    sa.Column('home_club_id', sa.Integer(), nullable=False),
    sa.Column('away_club_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'FINAL', 'POSTPONED', name='fixturestatus'), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweek.id'], ),
    sa.ForeignKeyConstraint(['home_club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixture_away_club_id'), ['away_club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixture_fixture_code'), ['fixture_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_fixture_gameweek_id'), ['gameweek_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixture_home_club_id'), ['home_club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixture_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixture_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixture_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixture_status'))
        batch_op.drop_index(batch_op.f('ix_fixture_source'))
        batch_op.drop_index(batch_op.f('ix_fixture_season_id'))
        batch_op.drop_index(batch_op.f('ix_fixture_home_club_id'))
        batch_op.drop_index(batch_op.f('ix_fixture_gameweek_id'))
        batch_op.drop_index(batch_op.f('ix_fixture_fixture_code'))
        batch_op.drop_index(batch_op.f('ix_fixture_away_club_id'))

    op.drop_table('fixture')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_status'))
        batch_op.drop_index(batch_op.f('ix_player_source'))
        batch_op.drop_index(batch_op.f('ix_player_position'))
        batch_op.drop_index(batch_op.f('ix_player_player_code'))
        batch_op.drop_index(batch_op.f('ix_player_club_id'))

    op.drop_table('player')
    with op.batch_alter_table('gameweek', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gameweek_season_id'))
        batch_op.drop_index(batch_op.f('ix_gameweek_number'))

    op.drop_table('gameweek')
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_code'))

    op.drop_table('season')
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_source'))
        batch_op.drop_index(batch_op.f('ix_club_club_code'))

    op.drop_table('club')
    # ### end Alembic commands ###
